# Generated by Django 6.0 on 2025-12-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_username', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('github_skills', models.JSONField(default=list)),
                ('linkedin_skills', models.JSONField(default=list)),
                ('final_skill_map', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
