# Generated by Django 6.0 on 2025-12-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_applicant_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('skill', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('javascript', 'JavaScript'), ('react', 'React'), ('sql', 'SQL'), ('git', 'Git'), ('problem_solving', 'Problem Solving'), ('communication', 'Communication'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('expected_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.interviewquestion')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('current_skill_focus', models.CharField(blank=True, max_length=50, null=True)),
                ('total_questions', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.application')),
                ('questions_asked', models.ManyToManyField(through='jobs.InterviewResponse', to='jobs.interviewquestion')),
            ],
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='interview_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.interviewsession'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewresponse',
            unique_together={('interview_session', 'question')},
        ),
    ]
